### ISSUE TITLE
feat: add special shell command support

### ISSUE THREAD

**Issue by murat-mehmet** [react-native-integrate/integrate#75]
Currently we need to use following task to delete a file:
```
  - task: shell
    label: Removing default App.tsx
    actions:
      - command: cmd /c del App.tsx
        when:
          PLATFORM: win32
      - command: rm ./App.tsx
        when:
          PLATFORM:
            $not: win32
```

We could simplify this by adding alias for some operations, currently only `delete`
